#!/usr/bin/env python3

import requests
from urllib.parse import urljoin
import os.path
import hashlib

index = open('index.md', 'w')
checksums = open('SHA1SUM', 'w')

checksum_url = 'https://www.virtualhere.com/sites/default/files/usbserver/SHA1SUM'
generic_builds = [
    'vhusbdarm', 'vhusbdarm64', 'vhusbdi386', 'vhusbdmips', 'vhusbdmipsel', 'vhusbdx86_64',
    'vhusbdwin64.exe', 'vhusbdwinarmw64.exe', 'vhusbdwinw64.exe',
    'VirtualHereServer.dmg', 'VirtualHereServerUniversal.dmg',
    'VirtualHere_4.6.5.qpkg',
]

session = requests.Session()

print('Downloading', checksum_url)
response = session.get(checksum_url)
response.raise_for_status()
for line in response.content.decode('utf-8').splitlines():
    checksum, filename = line.split()

    binary_url = urljoin(checksum_url, filename)
    filename = os.path.basename(binary_url)

    is_optimised = filename not in generic_builds
    if is_optimised:
        local_filename = os.path.join('optimised', filename)
    else:
        local_filename = os.path.join('generic', filename)
    try:
        os.mkdir(os.path.dirname(local_filename))
    except FileExistsError:
        pass

    print('Downloading', binary_url)
    response = session.get(binary_url)
    response.raise_for_status()
    assert(hashlib.new('sha1', response.content).hexdigest() == checksum)

    with open(local_filename, 'wb') as f:
       f.write(response.content)

    index.write(f'- [{filename}]({local_filename})\n')
    checksums.write(f'{checksum} *{local_filename}\n')

index.close()
checksums.close()
